db = db.getSiblingDB('fenli');
db.createCollection('fenliaddrs');
db.fenliaddrs.insertMany([
	{"name":"地下城与勇士", "product":["dnf"], "url":"//game.gtimg.cn/images/dnf/cp/"},
	{"name":"王者荣耀", "product":["wzry","pvp"], "url":"//game.gtimg.cn/images/yxzj/cp/"},
	{"name":"王者荣耀（社区，游戏内）", "product":["wzry_sq", "pvp_ingame"], "url":"//game.gtimg.cn/images/yxzj/ingame/cp/"},
	{"name":"御龙在天", "product":["ylzt"], "url":"//game.gtimg.cn/images/ylzt/cp/ "},
	{"name":"寻仙手游", "product":["xxsy"], "url":"//game.gtimg.cn/images/xxsy/cp/"},
	{"name":"龙之谷", "product":["dn","lzg"], "url":"//game.gtimg.cn/images/dn/cp/"},
	{"name":"乱世王者", "product":["slg", "lswz"], "url":"//game.gtimg.cn/images/slg/cp"},
	{"name":"三国群英传", "product":["bwzy"], "url":"//game.gtimg.cn/images/bwzy/cp/"},
	{"name":"魔力宝贝", "product":["moli"], "url":"//game.gtimg.cn/images/moli/cp/"},
	{"name":"心悦", "product":["xinyue"], "url":"//ossweb-img.qq.com/images/chanpin/tgclub/public/"},
	{"name":"择天记", "product":["zhetianji","ztj"], "url":"//game.gtimg.cn/images/zhetianji/cp/"},
	{"name":"火源计划", "product":["rf"], "url":"//game.gtimg.cn/images/rf/cp/"},
	{"name":"枪火游侠", "product":["qhyx"], "url":"//game.gtimg.cn/images/qhyx/cp/"},
	{"name":"极品飞车", "product":["nfsol"], "url":"//game.gtimg.cn/images/nfsol/cp/"},
	{"name":"战争雷霆", "product":["zzlt"], "url":"//game.gtimg.cn/images/zzlt/cp/"},
	{"name":"六龙争霸", "product":["ttcz"], "url":"//game.gtimg.cn/images/ttcz/cp/"},
	{"name":"穿越火线", "product":["cf"], "url":"//game.gtimg.cn/images/cf/cp/"},
	{"name":"穿越火线(手游)、掌火", "product":["cfm"], "url":"//game.gtimg.cn/images/cfm/cp/"},
	{"name":"TGP", "product":["tgp"], "url":"//ossweb-img.qq.com/images/chanpin/tgp/public/"},
	{"name":"疾风之刃", "product":["jf"], "url":"//game.gtimg.cn/images/jf/cp/"},
	{"name":"QQ飞车", "product":["speed"], "url":"//game.gtimg.cn/images/speed/cp/"},
	{"name":"QQ飞车(手游)", "product":["speedm"], "url":"//game.gtimg.cn/images/speedm/cp/"},
	{"name":"QQ华夏手游", "product":["hx"], "url":"//game.gtimg.cn/images/hx/cp/"},
	{"name":"天龙八部", "product":["tlbb"], "url":"//game.gtimg.cn/images/tlbb/cp/"},
	{"name":"逆战", "product":["nz"], "url":"//game.gtimg.cn/images/nz/cp/"},
	{"name":"使命召唤", "product":["cod","codo"], "url":"//game.gtimg.cn/images/codo/cp/"},
	{"name":"热血传奇", "product":["mir", "rxcq"], "url":"//game.gtimg.cn/images/mir/cp/"}
]);
